/*
 * AI Cost Calculator: interface text in English and Nepali
 * ------------------------------------------------------------------
 * Short labels, buttons and messages. The longer explanations live in
 * content.js. {name} marks a value filled in by the page; numbers arrive
 * already formatted for the language (Devanagari digits in Nepali).
 *
 * Nepali: written for this exhibit. Please have a native speaker read it
 * once before opening.
 */

export const STRINGS = {
  en: {
    /* Page titles and shared controls */
    'title.chat': 'AI Cost Calculator',
    appTitle: 'AI Cost Calculator',
    appSubtitle: 'Ask AI. See the energy, water, and emissions behind your query.',
    billTitle: 'Your AI query costs',
    receiptKicker: 'Your receipt',
    receiptHeading: 'What your question used',
    receiptIntro: 'The reply was free for you. Behind it, a data centre ran chips, cooled them with water and drew power from the grid. This is our estimate for that one exchange.',
    tokensInOut: 'Tokens in / out',
    receiptFoot: 'Estimate for one exchange. Real figures vary by model, data centre and grid.',
    electricity: 'Electricity',
    water: 'Water',
    carbon: 'Carbon',
    'est.text': 'How AI processes the text',
    'est.electricity': 'How electricity consumption is measured',
    'est.water': 'How the water consumption is measured',
    'est.carbon': 'How carbon impact is calculated',
    'title.references': 'References · AI Cost Calculator',
    referencesLink: 'References →',
    seeReferences: 'See all references',
    closingTitle: 'Small per question. Huge at scale.',
    closingText: 'Use it on purpose: ask for what you need, and pick a smaller model when it will do.',
    backToExhibit: '← Back to the calculator',
    'controls.language': 'Language',
    'controls.textSize': 'Larger text',
    skipToChat: 'Skip to the question box',
    skipToBill: 'Skip to your bill',

    /* Chat */
    lede: 'Ask anything. Then see what it cost.',
    yourQuestion: 'Your question',
    placeholder: 'Ask anything',
    send: 'Send',
    stop: 'Stop',
    templates: 'Sample prompts',
    conversation: 'Conversation',
    messages: 'Messages',
    seeCost: 'See how the cost is calculated',
    cardTitle: 'This answer wasn’t free for the planet',
    cardText: 'Every reply runs on chips in a data centre that use electricity and water and emit carbon. Here is what yours used.',
    thinking: 'Thinking {s} s',
    answerN: 'Answer {n}',
    stopped: 'Stopped. Tokens so far still count.',
    meter: '<strong>{in}</strong> in · <strong>{out}</strong> out',
    answerComplete: 'Answer complete.',
    typeFirst: 'Type a question first.',
    allUsed: 'That’s all {n} questions. See what it cost.',
    tooLong: 'Keep it under {n} characters.',

    /* Cost page */
    backToChat: '← Back to the chat',
    yourBill: 'Your bill',
    receiptLabel: 'Itemised receipt',
    noVisit: 'Ask a question first, then come back to see what it cost.',
    goAsk: 'Ask a question',
    howEstimate: 'How do we estimate this?',
    methodKicker: 'Method',
    howEstimateIntro: 'Four steps, each using your own question and reply. Open any step to see the working and the sources.',
    askAnother: 'Ask another question',
    startAgain: 'Start again',
    newChat: 'New chat',
    references: 'References',
    referencesIntro: 'Where every figure comes from.',
    usedFor: 'Used for:',
    citedIn: 'Cited in:',
    referenceN: 'Reference {n}: {short}',
    research: 'What research says',
    yourReading: 'Your reading',
    range: 'Range {r}',

    /* Tokens */
    tokensHeading: 'How the AI reads your text',
    tokenWord: 'Token',
    tokenDef:
      'A token is a small piece of text: a short word, part of a longer word, or a punctuation mark. The AI never sees letters or whole sentences, only tokens. Every token is counted, and every token is billed.',
    tokenExamplesLabel: 'The same sentence in English and in Nepali:',
    tokenAfter:
      'Nepali is cut into more pieces, so the same question costs more. Each AI model cuts text its own way; these pieces come from OpenAI’s tokenizer.',
    nTokens: '{c} tokens',
    tokensYours: 'Your conversation, in tokens',
    sent: 'Sent to the AI',
    written: 'Written by the AI',
    writtenNote: 'The answer, token by token. Writing costs more than reading.',
    hiddenNote: 'The exhibit’s hidden note, sent before your words · {c} tokens',
    tokens: 'tokens',
    inputBoxLabel: 'Your messages split into tokens',
    outputBoxLabel: 'The AI’s answers split into tokens',
    breakdown:
      '{typed} you typed + {rest} more: the exhibit’s hidden note to the AI, and the earlier conversation, which is sent again with every new question.',
    turnByTurn: 'Turn by turn',
    turn: 'Turn',
    typed: 'Typed',
    total: 'Total',
    qN: 'Q{n}',
    groupQ: 'Q{n} · {c} typed',
    groupA: 'A{n} · {c} tokens',
    hiddenThinking: ' ({c} hidden thinking)',
    footSample: '† Sample: counted on this computer.',
    footStopped: '* Stopped early: output counted on this computer.',

    /* Calculations */
    'calc.read': '{n} tokens read × {k} Wh each',
    'calc.written': '{n} tokens written × {k} Wh each',
    'calc.heat': '{wh} Wh × {k} joules per Wh',
    workingLabel: 'Your numbers',
    sourceLabel: 'Where the numbers come from',
    sourceMoney:
      'AI companies sell their models by the token, at a published price per million tokens. {model} costs ${in} per million tokens read and ${out} per million written, from {company}’s official price list.',
    'calc.water': '{wh} Wh × ({a} + {b}) mL per Wh',
    'calc.waterKey': '{a} for cooling, {b} at the power plant',
    'calc.carbon': '{wh} Wh × {k} g CO₂e per Wh',
    'calc.carbonKey': '{grid} grid',
    'calc.moneyIn': '{n} read × ${p} per million',
    'calc.moneyOut': '{n} written × ${p} per million',
    'calc.scale': '{wh} Wh × {k} prompts',
    'calc.perDay': '{v} a day',
    'calc.rangeKey': 'Range ×{lo} to ×{hi}, from other studies',
    worldAverage: 'world-average',
    'n.2_5bn': '2.5 billion',

    /* Readings */
    'label.electricity': 'Your electricity',
    'label.heat': 'Your heat',
    'label.water': 'Your water',
    'label.carbon': 'Your carbon, {grid} grid',
    'label.moneyLive': 'Actual API cost',
    'label.moneySample': 'Price of these tokens',
    'label.scale': 'Your conversation × 2.5 billion, per day',
    notEstimate: 'Not an estimate.',
    notCharged: 'Sample answers were not charged.',
    scalePlus: 'plus {w} water, {c} CO₂e',
    'analogy.phone': '<strong>{v}</strong> of a phone charge',
    'analogy.bulb': '<strong>{v}</strong> of a {w} W bulb',
    'analogy.car': '<strong>{v}</strong> in a petrol car {cite}',
    'analogy.money': '$1 pays for <strong>{v}</strong> of these',
    'water.ofDrop': '<strong>{v}</strong> of a drop',
    'water.drop': '<strong>{v}</strong> drop',
    'water.drops': '<strong>{v}</strong> drops',
    'water.tsp': '<strong>{v}</strong> teaspoon',
    'water.tsps': '<strong>{v}</strong> teaspoons',
    'water.ofGlass': '<strong>{v}</strong> of a glass',
    'water.glasses': '<strong>{v}</strong> glasses',
    'time.ofSecond': '{v} of a second',
    'time.seconds': '{v} seconds',
    'time.minutes': '{v} minutes',
    'time.hours': '{v} hours',
    'dist.cm': '{v} cm',
    'dist.m': '{v} metres',
    'dist.km': '{v} km',
    'unit.millionL': 'million L',
    moneyPrices: '{model}: <b>${in}</b> per million tokens read, <b>${out}</b> per million written ({r}× more).',
    noPrice: 'No price is set for {model} in config.js.',

    /* Receipt */
    'r.model': 'Model: {m}',
    'r.live': 'Live answers',
    'r.mixed': 'Live and sample answers',
    'r.sample': 'Sample answers',
    'r.tokens': 'Tokens',
    'r.sent': 'Q{n} sent',
    'r.written': 'Q{n} written',
    'r.markSample': ' (sample)',
    'r.markStopped': ' (stopped)',
    'r.thinking': 'incl. {n} hidden thinking tokens',
    'r.input': 'Input tokens',
    'r.output': 'Output tokens',
    'r.total': 'Total tokens',
    'r.estimated': 'Estimated use',
    'r.costLive': 'ACTUAL API COST',
    'r.costSample': 'PRICE OF THESE TOKENS',
    'r.in': '{n} in × ${p}/M',
    'r.out': '{n} out × ${p}/M',
    'r.people': '× {n} people',
    'r.thanks': '*** THANK YOU ***',
    estimatesNote: 'Electricity, heat, water and carbon are estimates. How we get them is below.',

    /* Disclaimer */
    disclaimerHeading: 'These are estimates',
    disclaimer1:
      'Token counts come straight from the AI provider. Electricity, water and carbon are estimates built on published research.',
    disclaimer2:
      'No AI company publishes the energy used per token, and we can’t know which data center answered you or how its power was made. Training the model and making the chips are not included.',
    disclaimer3: 'Read the physical numbers as a rough size, not a meter reading.',

    /* Idle reset */
    stillThere: 'Still there?',
    startingOver: 'Starting over in {n} seconds.',
    stillHere: 'I’m still here',
  },

  ne: {
    'title.chat': 'एआई लागत क्याल्कुलेटर',
    appTitle: 'एआई लागत क्याल्कुलेटर',
    appSubtitle: 'एआईलाई सोध्नुहोस्। तपाईंको प्रश्नपछाडिको ऊर्जा, पानी र उत्सर्जन हेर्नुहोस्।',
    billTitle: 'तपाईंको एआई प्रश्नको लागत',
    receiptKicker: 'तपाईंको बिल',
    receiptHeading: 'तपाईंको प्रश्नले के खर्च गर्‍यो',
    receiptIntro: 'उत्तर तपाईंलाई निःशुल्क थियो। तर त्यसका पछाडि एउटा डेटा सेन्टरले चिप चलायो, तिनलाई पानीले चिसो पार्‍यो र ग्रिडबाट बिजुली लियो। यो त्यही एउटा कुराकानीको हाम्रो अनुमान हो।',
    tokensInOut: 'पठाइएको / लेखिएको टोकन',
    receiptFoot: 'एउटा कुराकानीको अनुमान। वास्तविक अङ्क मोडेल, डेटा सेन्टर र ग्रिडअनुसार फरक पर्छ।',
    electricity: 'बिजुली',
    water: 'पानी',
    carbon: 'कार्बन',
    'est.text': 'एआईले पाठ कसरी प्रशोधन गर्छ',
    'est.electricity': 'बिजुली खपत कसरी नापिन्छ',
    'est.water': 'पानी खपत कसरी नापिन्छ',
    'est.carbon': 'कार्बन प्रभाव कसरी गणना गरिन्छ',
    'title.references': 'सन्दर्भ सामग्री · एआई लागत क्याल्कुलेटर',
    referencesLink: 'सन्दर्भ सामग्री →',
    seeReferences: 'सबै सन्दर्भ हेर्नुहोस्',
    closingTitle: 'एउटा प्रश्नमा सानो। करोडौँ प्रश्नमा ठूलो।',
    closingText: 'सोचेर प्रयोग गर्नुहोस्: चाहिएको मात्र सोध्नुहोस्, र सानो मोडेलले पुग्छ भने त्यही रोज्नुहोस्।',
    backToExhibit: '← क्याल्कुलेटरमा फर्कनुहोस्',
    'controls.language': 'भाषा',
    'controls.textSize': 'ठूलो अक्षर',
    skipToChat: 'प्रश्न लेख्ने ठाउँमा जानुहोस्',
    skipToBill: 'तपाईंको बिलमा जानुहोस्',

    lede: 'जे पनि सोध्नुहोस्। अनि त्यसको लागत हेर्नुहोस्।',
    yourQuestion: 'तपाईंको प्रश्न',
    placeholder: 'जे पनि सोध्नुहोस्',
    send: 'पठाउनुहोस्',
    stop: 'रोक्नुहोस्',
    templates: 'नमुना प्रश्नहरू',
    conversation: 'कुराकानी',
    messages: 'सन्देशहरू',
    seeCost: 'लागत कसरी निकालियो हेर्नुहोस्',
    cardTitle: 'यो उत्तर पृथ्वीका लागि निःशुल्क थिएन',
    cardText: 'हरेक उत्तर डेटा सेन्टरका चिपमा चल्छ, जसले बिजुली र पानी खर्च गर्छन् र कार्बन निकाल्छन्। तपाईंको उत्तरले यति खर्च गर्‍यो।',
    thinking: 'सोच्दै {s} सेकेन्ड',
    answerN: 'उत्तर {n}',
    stopped: 'रोकियो। अहिलेसम्मका टोकन पनि गनिन्छन्।',
    meter: '<strong>{in}</strong> पठाइएको · <strong>{out}</strong> लेखिएको',
    answerComplete: 'उत्तर पूरा भयो।',
    typeFirst: 'पहिले प्रश्न लेख्नुहोस्।',
    allUsed: '{n} वटै प्रश्न सकिए। अब लागत हेर्नुहोस्।',
    tooLong: '{n} अक्षरभित्र लेख्नुहोस्।',

    backToChat: '← कुराकानीमा फर्कनुहोस्',
    yourBill: 'तपाईंको बिल',
    receiptLabel: 'विस्तृत बिल',
    noVisit: 'पहिले एउटा प्रश्न सोध्नुहोस्, अनि लागत हेर्न यहाँ फर्कनुहोस्।',
    goAsk: 'प्रश्न सोध्नुहोस्',
    howEstimate: 'हामी यो कसरी अनुमान गर्छौं?',
    methodKicker: 'विधि',
    howEstimateIntro: 'चार चरण, हरेकमा तपाईंकै प्रश्न र उत्तर प्रयोग गरिएको छ। हिसाब र स्रोत हेर्न कुनै पनि चरण खोल्नुहोस्।',
    askAnother: 'अर्को प्रश्न सोध्नुहोस्',
    startAgain: 'फेरि सुरु गर्नुहोस्',
    newChat: 'नयाँ कुराकानी',
    references: 'सन्दर्भ सामग्री',
    referencesIntro: 'हरेक अङ्क कहाँबाट आयो।',
    usedFor: 'प्रयोग:',
    citedIn: 'उल्लेख:',
    referenceN: 'सन्दर्भ {n}: {short}',
    research: 'अनुसन्धानले के भन्छ',
    yourReading: 'तपाईंको खपत',
    range: 'दायरा {r}',

    tokensHeading: 'एआईले तपाईंको पाठ कसरी पढ्छ',
    tokenWord: 'टोकन',
    tokenDef:
      'टोकन भनेको पाठको सानो टुक्रा हो: छोटो शब्द, लामो शब्दको एक भाग, वा चिह्न। एआईले अक्षर वा पूरा वाक्य देख्दैन, टोकन मात्र देख्छ। हरेक टोकन गनिन्छ, र हरेक टोकनको पैसा लाग्छ।',
    tokenExamplesLabel: 'उही वाक्य अङ्ग्रेजी र नेपालीमा:',
    tokenAfter:
      'नेपाली वाक्य धेरै टुक्रामा काटिन्छ, त्यसैले उही प्रश्नको लागत बढी हुन्छ। हरेक एआई मोडेलले पाठलाई आफ्नै तरिकाले काट्छ; यहाँका टुक्रा OpenAI को टोकनाइजरबाट हुन्।',
    nTokens: '{c} टोकन',
    tokensYours: 'तपाईंको कुराकानी, टोकनमा',
    sent: 'एआईलाई पठाइएको',
    written: 'एआईले लेखेको',
    writtenNote: 'उत्तर, एक-एक टोकन गरेर। लेख्नु पढ्नुभन्दा महँगो छ।',
    hiddenNote: 'तपाईंका शब्दभन्दा पहिले पठाइने प्रदर्शनीको लुकेको निर्देशन · {c} टोकन',
    tokens: 'टोकन',
    inputBoxLabel: 'टोकनमा टुक्र्याइएका तपाईंका सन्देश',
    outputBoxLabel: 'टोकनमा टुक्र्याइएका एआईका उत्तर',
    breakdown:
      '{typed} तपाईंले टाइप गरेको + {rest} थप: प्रदर्शनीले एआईलाई दिने लुकेको निर्देशन, र अघिल्लो कुराकानी, जुन हरेक नयाँ प्रश्नसँग फेरि पठाइन्छ।',
    turnByTurn: 'प्रश्नैपिच्छे',
    turn: 'पालो',
    typed: 'टाइप गरिएको',
    total: 'जम्मा',
    qN: 'प्र. {n}',
    groupQ: 'प्रश्न {n} · {c} टाइप गरिएको',
    groupA: 'उत्तर {n} · {c} टोकन',
    hiddenThinking: ' ({c} लुकेको सोच)',
    footSample: '† नमुना: यही कम्प्युटरमा गनिएको।',
    footStopped: '* बीचमै रोकिएको: उत्तर यही कम्प्युटरमा गनिएको।',

    'calc.read': '{n} पढिएका टोकन × प्रति टोकन {k} Wh',
    'calc.written': '{n} लेखिएका टोकन × प्रति टोकन {k} Wh',
    'calc.heat': '{wh} Wh × प्रति Wh {k} जुल',
    workingLabel: 'तपाईंका अङ्क',
    sourceLabel: 'अङ्क कहाँबाट आए',
    sourceMoney:
      'एआई कम्पनीहरूले आफ्ना मोडेल टोकनका आधारमा, प्रति दस लाख टोकनको प्रकाशित मूल्यमा बेच्छन्। {company} को आधिकारिक मूल्य सूचीअनुसार {model} मा पढिएका प्रति दस लाख टोकन ${in} र लेखिएका प्रति दस लाख टोकन ${out} लाग्छ।',
    'calc.water': '{wh} Wh × प्रति Wh ({a} + {b}) mL',
    'calc.waterKey': '{a} चिसो पार्न, {b} विद्युत् केन्द्रमा',
    'calc.carbon': '{wh} Wh × प्रति Wh {k} g CO₂e',
    'calc.carbonKey': '{grid} ग्रिड',
    'calc.moneyIn': '{n} पढिएका × प्रति दस लाख ${p}',
    'calc.moneyOut': '{n} लेखिएका × प्रति दस लाख ${p}',
    'calc.scale': '{wh} Wh × {k} प्रश्न',
    'calc.perDay': 'दिनमा {v}',
    'calc.rangeKey': 'अरू अध्ययनका आधारमा दायरा ×{lo} देखि ×{hi} सम्म',
    worldAverage: 'विश्वको औसत',
    'n.2_5bn': '२.५ अर्ब',

    'label.electricity': 'तपाईंको बिजुली',
    'label.heat': 'तपाईंको ताप',
    'label.water': 'तपाईंको पानी',
    'label.carbon': 'तपाईंको कार्बन, {grid} ग्रिड',
    'label.moneyLive': 'वास्तविक एपीआई खर्च',
    'label.moneySample': 'यी टोकनको मूल्य',
    'label.scale': 'तपाईंको कुराकानी × २.५ अर्ब, दैनिक',
    notEstimate: 'यो अनुमान होइन।',
    notCharged: 'नमुना उत्तरको पैसा लागेको छैन।',
    scalePlus: 'साथै {w} पानी, {c} CO₂e',
    'analogy.phone': 'फोनको एक पटकको चार्जको <strong>{v}</strong>',
    'analogy.bulb': '{w} W को बल्ब <strong>{v}</strong> बाल्न पुग्ने',
    'analogy.car': 'पेट्रोल कारको <strong>{v}</strong> यात्रा बराबर {cite}',
    'analogy.money': '$१ मा यस्ता <strong>{v}</strong> वटा',
    'water.ofDrop': 'एक थोपाको <strong>{v}</strong> भाग',
    'water.drop': '<strong>{v}</strong> थोपा',
    'water.drops': '<strong>{v}</strong> थोपा',
    'water.tsp': '<strong>{v}</strong> चिया चम्चा',
    'water.tsps': '<strong>{v}</strong> चिया चम्चा',
    'water.ofGlass': 'एक गिलासको <strong>{v}</strong>',
    'water.glasses': '<strong>{v}</strong> गिलास',
    'time.ofSecond': '{v} सेकेन्ड',
    'time.seconds': '{v} सेकेन्ड',
    'time.minutes': '{v} मिनेट',
    'time.hours': '{v} घण्टा',
    'dist.cm': '{v} सेमी',
    'dist.m': '{v} मिटर',
    'dist.km': '{v} किमी',
    'unit.millionL': 'मिलियन L',
    moneyPrices: '{model}: पढिएका प्रति दस लाख टोकन <b>${in}</b>, लेखिएका प्रति दस लाख <b>${out}</b> ({r} गुणा बढी)।',
    noPrice: 'config.js मा {model} को मूल्य राखिएको छैन।',

    'r.model': 'मोडेल: {m}',
    'r.live': 'लाइभ उत्तर',
    'r.mixed': 'लाइभ र नमुना उत्तर',
    'r.sample': 'नमुना उत्तर',
    'r.tokens': 'टोकन',
    'r.sent': 'प्र. {n} पठाइएको',
    'r.written': 'प्र. {n} लेखिएको',
    'r.markSample': ' (नमुना)',
    'r.markStopped': ' (रोकिएको)',
    'r.thinking': '{n} लुकेको सोचको टोकन समेत',
    'r.input': 'इनपुट टोकन',
    'r.output': 'आउटपुट टोकन',
    'r.total': 'जम्मा टोकन',
    'r.estimated': 'अनुमानित खपत',
    'r.costLive': 'वास्तविक एपीआई खर्च',
    'r.costSample': 'यी टोकनको मूल्य',
    'r.in': '{n} इनपुट × ${p}/M',
    'r.out': '{n} आउटपुट × ${p}/M',
    'r.people': '× {n} जना',
    'r.thanks': '*** धन्यवाद ***',
    estimatesNote: 'बिजुली, ताप, पानी र कार्बन अनुमान हुन्। तिनलाई कसरी निकालियो, तल हेर्नुहोस्।',

    disclaimerHeading: 'यी अनुमान मात्र हुन्',
    disclaimer1:
      'टोकनको सङ्ख्या सिधै एआई कम्पनीबाट आउँछ। बिजुली, पानी र कार्बन भने प्रकाशित अनुसन्धानमा आधारित अनुमान हुन्।',
    disclaimer2:
      'कुनै पनि एआई कम्पनीले प्रति टोकन कति ऊर्जा लाग्छ भनेर सार्वजनिक गर्दैन, र तपाईंको उत्तर कुन डेटा सेन्टरले दियो वा त्यहाँको बिजुली कसरी निकालियो भन्ने हामीलाई थाहा हुँदैन। मोडेलको तालिम र चिप बनाउँदाको खपत यसमा गनिएको छैन।',
    disclaimer3: 'यी भौतिक अङ्कलाई मिटरको ठ्याक्कै रिडिङ होइन, मोटामोटी आकारका रूपमा बुझ्नुहोस्।',

    stillThere: 'अझै हुनुहुन्छ?',
    startingOver: '{n} सेकेन्डमा फेरि सुरु हुँदैछ।',
    stillHere: 'म यहीँ छु',
  },
};
